In [2]:
# @hidden_cell
# The project token is an authorization token that is used to access project resources like data sources, connections, and used by platform APIs.
from project_lib import Project
project = Project(project_id='6a2c2f45-a184-4ae6-a9d3-3a1e5ad4e537', project_access_token='p-d7bc36affb87b44b1b105d6290da63dfda68762b')
pc = project.project_context

In [8]:
import matplotlib
from matplotlib import pylab as plt
import numpy as np
import pandas as pd

In [16]:

import types
import pandas as pd
from ibm_botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_acece927b4ba44519751d49fd8861145 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='as0X-g5so9ras2AQdxGGQ7-cHrl7uuAmjsmgdU3C0ebW',
    ibm_auth_endpoint="https://iam.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_acece927b4ba44519751d49fd8861145.get_object(Bucket='tjbotai-donotdelete-pr-82k5ks6cxagfsz',Key='Wetter-Linz-Hoersching.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df = pd.read_csv(body, parse_dates=['DateTime [UTC]'])
df.head()

DateTime [UTC]    T   Td    ff     dd       P  Pstat    rF  rSD   RR
0 2016-12-31 23:00:00 -5.1 -5.5  1.11  135.0  1032.6    NaN  97.0  0.0  0.0
1 2017-01-01 00:00:00 -5.1 -5.5  0.56    NaN  1031.7    NaN  97.0  0.0  0.0
2 2017-01-01 01:00:00 -5.2 -5.7  1.11  315.0  1031.1    NaN  97.0  0.0  0.0
3 2017-01-01 02:00:00 -5.6 -6.1  1.11  315.0  1030.5    NaN  96.0  0.0  0.0
4 2017-01-01 03:00:00 -5.8 -6.3  1.11  270.0  1029.8    NaN  96.0  0.0  0.0

In [17]:
df = df.drop(columns=['Pstat']).dropna().set_index('DateTime [UTC]')
df

T   Td        ff     dd       P    rF  rSD   RR
DateTime [UTC]                                                         
2016-12-31 23:00:00  -5.1 -5.5  1.110000  135.0  1032.6  97.0  0.0  0.0
2017-01-01 01:00:00  -5.2 -5.7  1.110000  315.0  1031.1  97.0  0.0  0.0
2017-01-01 02:00:00  -5.6 -6.1  1.110000  315.0  1030.5  96.0  0.0  0.0
2017-01-01 03:00:00  -5.8 -6.3  1.110000  270.0  1029.8  96.0  0.0  0.0
2017-01-01 05:00:00  -6.3 -6.8  1.110000  270.0  1028.9  96.0  0.0  0.0
2017-01-01 06:00:00  -6.6 -7.2  1.110000  225.0  1028.5  95.0  0.0  0.0
2017-01-01 07:00:00  -6.2 -6.8  1.390000  270.0  1028.4  96.0  0.0  0.0
2017-01-01 08:00:00  -6.2 -6.7  1.110000  135.0  1028.1  96.0  0.0  0.0
2017-01-01 09:00:00  -5.8 -6.3  1.110000  270.0  1027.7  96.0  0.0  0.0
2017-01-01 12:00:00  -5.3 -5.7  1.110000  225.0  1025.0  97.0  0.0  0.0
2017-01-01 13:00:00  -5.1 -5.7  1.110000  315.0  1024.3  96.0  0.0  0.0
2017-01-01 14:00:00  -4.9 -5.4  1.390000  225.0  1023.9  96.0  0.0  0.0
2017-01-01 15:00:00  -4.9 -5.4  1.110000  225.0  1023.7  96.0  0.0  0.0
2017-01-01 16:00:00  -4.9 -5.4  1.110000  270.0  1023.4  96.0  0.0  0.0
2017-01-01 17:00:00  -5.3 -5.8  1.110000  270.0  1023.3  96.0  0.0  0.0
2017-01-01 18:00:00  -5.7 -6.3  1.390000  225.0  1023.6  96.0  0.0  0.0
2017-01-01 19:00:00  -6.0 -6.5  1.110000  225.0  1023.5  96.0  0.0  0.0
2017-01-01 20:00:00  -5.8 -6.4  1.110000   90.0  1023.4  96.0  0.0  0.0
2017-01-01 22:00:00  -6.5 -7.2  1.110000  315.0  1023.2  95.0  0.0  0.0
2017-01-01 23:00:00  -6.6 -7.4  1.390000  225.0  1023.2  94.0  0.0  0.0
2017-01-02 00:00:00  -6.9 -7.7  1.390000  225.0  1023.0  94.0  0.0  0.0
2017-01-02 01:00:00  -6.5 -7.2  1.390000  225.0  1022.8  95.0  0.0  0.0
2017-01-02 02:00:00  -6.1 -6.8  2.220000  270.0  1022.6  95.0  0.0  0.0
2017-01-02 03:00:00  -7.1 -7.8  1.390000  270.0  1022.7  95.0  0.0  0.0
2017-01-02 04:00:00  -7.6 -8.4  1.110000  270.0  1022.6  94.0  0.0  0.0
2017-01-02 05:00:00  -8.1 -9.2  1.390000  225.0  1022.7  92.0  0.0  0.0
2017-01-02 06:00:00  -8.6 -9.7  0.560000  270.0  1023.0  92.0  0.0  0.0
2017-01-02 08:00:00  -5.8 -6.4  4.170000  270.0  1022.6  96.0  0.0  0.0
2017-01-02 09:00:00  -5.2 -5.9  2.220000  315.0  1022.6  95.0  0.0  0.0
2017-01-02 10:00:00  -3.6 -4.1  6.670000  270.0  1022.0  96.0  0.0  0.0
...                   ...  ...       ...    ...     ...   ...  ...  ...
2018-11-09 08:00:00  10.2  7.3  2.222222   90.0  1019.0  82.0  0.0  0.0
2018-11-09 09:00:00  10.4  7.5  2.500000   90.0  1018.7  82.0  0.0  0.0
2018-11-09 10:00:00  10.6  7.5  2.500000   90.0  1018.8  81.0  0.0  0.0
2018-11-09 11:00:00  10.7  7.6  1.111111   90.0  1018.5  82.0  0.0  0.0
2018-11-09 12:00:00  11.1  7.3  1.388889   90.0  1018.0  78.0  0.0  0.0
2018-11-09 13:00:00  11.0  7.3  1.111111   45.0  1017.6  78.0  0.0  0.0
2018-11-09 14:00:00  10.9  7.3  1.388889   90.0  1017.2  78.0  0.0  0.0
2018-11-09 15:00:00  10.6  7.4  2.222222   90.0  1016.8  81.0  0.0  0.0
2018-11-09 16:00:00  10.3  7.5  2.500000   90.0  1016.9  83.0  0.0  0.0
2018-11-09 17:00:00  10.3  7.4  1.388889   90.0  1017.1  83.0  0.0  0.0
2018-11-09 18:00:00  10.3  7.5  2.500000   90.0  1016.9  83.0  0.0  0.0
2018-11-09 19:00:00  10.2  7.5  2.500000   90.0  1016.7  83.0  0.0  0.0
2018-11-09 20:00:00   9.9  7.4  2.500000   90.0  1016.6  84.0  0.0  0.0
2018-11-09 21:00:00   9.8  7.6  2.500000   90.0  1016.3  86.0  0.0  0.0
2018-11-09 22:00:00   9.7  7.6  3.055556   90.0  1016.1  87.0  0.0  0.0
2018-11-09 23:00:00   9.7  7.7  2.500000   90.0  1015.6  88.0  0.0  0.0
2018-11-10 01:00:00   9.5  8.0  1.388889   90.0  1015.0  90.0  0.0  0.0
2018-11-10 02:00:00   9.4  8.2  1.388889   90.0  1014.6  93.0  0.0  0.0
2018-11-10 03:00:00   9.3  8.2  2.222222   90.0  1014.3  92.0  0.0  0.0
2018-11-10 04:00:00   9.3  7.6  2.222222   90.0  1014.1  89.0  0.0  0.0
2018-11-10 05:00:00   9.0  7.3  1.388889   45.0  1013.9  89.0  0.0  0.0
2018-11-10 06:00:00   9.0  7.4  1.388889   90.0  1013.9  90.0  0.0  0.0
2018-11-10 07:00:00   9.0  7.3  1.388889   90.0  1014.1  89.0  0

In [18]:
data = df.iloc[0:6000:2]

In [19]:
X = data[['T','P','rF']]
Y = data['Td']

In [24]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_predict, KFold
from sklearn.metrics import r2_score, mean_squared_error

In [26]:
lr = LinearRegression()
y_pred_lr = cross_val_predict(lr, X, Y, cv=KFold(3, random_state=1))
lr.fit(X,Y)
r2_score(Y, y_pred_lr), np.sqrt(mean_squared_error(Y, y_pred_lr)), np.max(np.abs(Y-y_pred_lr))

(0.98362928752298751, 0.96412532092270919, 9.47581544865651)

In [28]:
from sklearn.neural_network import MLPRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [35]:
nn = Pipeline([
    ('scale', StandardScaler()),
    ('mlp', MLPRegressor(
        hidden_layer_sizes = [5,5,5], 
        max_iter = 1000
    ))
])

In [36]:
nn.fit(X,Y)

Pipeline(memory=None,
     steps=[('scale', StandardScaler(copy=True, with_mean=True, with_std=True)), ('mlp', MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=[5, 5, 5], learning_rate='constant',
       learning_ra...=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False))])

In [ ]:
y_pred_nn = cross_val_predict(nn, X, Y, cv=KFold(3, random_state=1))
nn.fit(X,Y)
r2_score(Y, y_pred_nn), np.sqrt(mean_squared_error(Y, y_pred_nn)), np.max(np.abs(Y-y_pred_nn))

In [37]:
from sklearn.preprocessing import PolynomialFeatures

In [42]:
pr=Pipeline([
    ('ploy', PolynomialFeatures(degree=4)),
    ('lr', LinearRegression())
])

In [43]:
y_pred_pr = cross_val_predict(pr, X, Y, cv=KFold(3, random_state=1))
r2_score(Y, y_pred_pr), np.sqrt(mean_squared_error(Y, y_pred_pr)), np.max(np.abs(Y-y_pred_pr))

(0.9996595820584836, 0.1390291664889492, 3.9706142711598655)

# MNIST Data

In [1]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()

/opt/conda/envs/DSX-Python35/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/opt/conda/envs/DSX-Python35/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/opt/conda/envs/DSX-Python35/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/opt/conda/envs/DSX-Python35/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


# Deep Learning with Keras

In [2]:
import keras
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense

In [3]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train_classes, y_test_classes = train_test_split(digits.data, digits.target, test_size=0.33, random_state=1)

In [6]:
X_train.shape

(1203, 64)

In [8]:
X_test.shape

(594, 64)

In [9]:
y_train_classes

array([1, 9, 0, ..., 9, 1, 5])

In [14]:
# OneHot coding 
y_train = to_categorical(y_train_classes)
y_test = to_categorical(y_test_classes)

In [11]:
y_train.shape

(1203, 10)

In [12]:
y_train[1]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.])

In [15]:
mlp = Sequential()
mlp.add( Dense(128, activation='relu', input_shape=(64,)) )
mlp.add( Dense(128, activation='relu'))
mlp.add( Dense(10, activation='softmax') )
mlp.compile(
    loss= keras.losses.categorical_crossentropy,
    optimizer = keras.optimizers.Adam(),
    metrics = ['accuracy']
)

In [21]:
mlp.fit(
    X_train, y_train,
    batch_size = 64,
    epochs = 50,
    verbose = 1, 
    validation_data=(X_test, y_test)
)

Train on 1203 samples, validate on 594 samples
Epoch 1/50
1203/1203 [==============================] - 0s 145us/step - loss: 0.0054 - acc: 1.0000 - val_loss: 0.0676 - val_acc: 0.9747
Epoch 2/50
1203/1203 [==============================] - 0s 91us/step - loss: 0.0049 - acc: 1.0000 - val_loss: 0.0707 - val_acc: 0.9731
Epoch 3/50
1203/1203 [==============================] - 0s 151us/step - loss: 0.0042 - acc: 1.0000 - val_loss: 0.0667 - val_acc: 0.9747
Epoch 4/50
1203/1203 [==============================] - 0s 95us/step - loss: 0.0037 - acc: 1.0000 - val_loss: 0.0661 - val_acc: 0.9747
Epoch 5/50
1203/1203 [==============================] - 0s 148us/step - loss: 0.0033 - acc: 1.0000 - val_loss: 0.0672 - val_acc: 0.9747
Epoch 6/50
1203/1203 [==============================] - 0s 95us/step - loss: 0.0030 - acc: 1.0000 - val_loss: 0.0644 - val_acc: 0.9747
Epoch 7/50
1203/1203 [==============================] - 0s 96us/step - loss: 0.0027 - acc: 1.0000 - val_loss: 0.0644 - val_acc: 0.9747
Epoch

In [22]:
mlp.predict(X_test[:2])

array([[  1.08965399e-10,   9.98627901e-01,   1.57720478e-06,
          2.73402652e-08,   4.60455368e-07,   2.87192819e-07,
          3.21270841e-06,   3.87887638e-07,   1.36629597e-03,
          9.60793556e-10],
       [  2.82334639e-07,   1.70471779e-07,   4.05736864e-05,
          1.58408842e-08,   1.69222663e-08,   9.93413508e-01,
          2.79791852e-08,   6.14842866e-03,   3.97056632e-04,
          9.82825110e-09]], dtype=float32)

In [23]:
mlp.predict_classes(X_test[:2])

array([1, 5])

In [36]:
from keras.layers import Conv2D, Flatten, Dropout, BatchNormalization, MaxPooling2D

In [30]:
X_train_cnn = X_train.reshape(X_train.shape[0],8,8,1)
X_test_cnn = X_test.reshape(X_test.shape[0],8,8,1)

In [31]:
X_train_cnn.shape

(1203, 8, 8, 1)

In [37]:
cnn = Sequential()

cnn.add( Conv2D(filters=32, kernel_size=(2,2), strides=(1,1), activation='relu', input_shape = (8,8,1)))

cnn.add( Conv2D(filters=32, kernel_size=(2,2), strides=(1,1), activation='relu'))

cnn.add ( MaxPooling2D(pool_size =(2,2)))

cnn.add ( Dropout(0.25))

cnn.add ( Flatten() )

cnn.add( Dense(128, activation='relu'))

cnn.add( BatchNormalization() )

cnn.add( Dense(10, activation='softmax') )

cnn.compile(
    loss= keras.losses.categorical_crossentropy,
    optimizer = keras.optimizers.Adam(),
    metrics = ['accuracy']
)


In [38]:
cnn.fit(
    X_train_cnn, y_train,
    batch_size = 64,
    epochs = 50,
    verbose = 1, 
    validation_data=(X_test_cnn, y_test)
)

Train on 1203 samples, validate on 594 samples
Epoch 1/50
1203/1203 [==============================] - 1s 772us/step - loss: 1.9569 - acc: 0.3566 - val_loss: 0.6319 - val_acc: 0.8687
Epoch 2/50
1203/1203 [==============================] - 1s 651us/step - loss: 0.7560 - acc: 0.7706 - val_loss: 0.3304 - val_acc: 0.9125
Epoch 3/50
1203/1203 [==============================] - 1s 586us/step - loss: 0.3786 - acc: 0.8936 - val_loss: 0.2511 - val_acc: 0.9360
Epoch 4/50
1203/1203 [==============================] - 1s 586us/step - loss: 0.2776 - acc: 0.9227 - val_loss: 0.1898 - val_acc: 0.9495
Epoch 5/50
1203/1203 [==============================] - 1s 584us/step - loss: 0.1806 - acc: 0.9568 - val_loss: 0.1562 - val_acc: 0.9630
Epoch 6/50
1203/1203 [==============================] - 1s 653us/step - loss: 0.1620 - acc: 0.9643 - val_loss: 0.1105 - val_acc: 0.9815
Epoch 7/50
1203/1203 [==============================] - 1s 588us/step - loss: 0.1269 - acc: 0.9726 - val_loss: 0.1162 - val_acc: 0.9781
E

In [39]:
from keras import datasets

In [40]:
data=datasets.mnist.load_data()

11493376/11490434 [==============================] - 11s 1us/step


((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ..., 
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ..., 
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ..., 
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ..., 
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ..., 
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0,

## Store 

In [41]:
fn = 'cnn.h5'

In [42]:
cnn.save(fn)

In [46]:
!ls -al

total 1028
drwxr-x--- 2 dsxuser dsxuser   4096 Jan 21 10:03 .
drwx------ 1 dsxuser dsxuser   4096 Jan 21 09:16 ..
-rw-r----- 1 dsxuser dsxuser 557784 Jan 21 10:03 cnn.h5
-rw-r----- 1 dsxuser dsxuser 481767 Jan 21 10:03 cnn.tgz


In [44]:
import os

In [45]:
os.system('tar cvfz cnn.tgz cnn.h5')

0